# Generated by Django 5.2.13 on 2026-05-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(editable=False)),
                ('price_at_time', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('closed_at', models.DateTimeField(editable=False, null=True)),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('ticket_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pos.ticket')),
            ],
        ),
    ]
