# Generated by Django 5.2.13 on 2026-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_ticket_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='closed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
